webtalk_init -webtalk_dir C:/Users/bartk/OneDrive - Vysok uen technick v Brn/kola/Druh ronk/2. semester/DE1/Digital-electronics-1/03-vivado/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_rst_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 29 22:29:37 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35309eb8-ac90-40ee-984b-ae32f0eeb2e2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a195a66ddeba4a1d9d8d8ed6f52004c3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6400_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4126019558 -regid "" -xml C:/Users/bartk/OneDrive - Vysok uen technick v Brn/kola/Druh ronk/2. semester/DE1/Digital-electronics-1/03-vivado/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_rst_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/bartk/OneDrive - Vysok uen technick v Brn/kola/Druh ronk/2. semester/DE1/Digital-electronics-1/03-vivado/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_rst_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/bartk/OneDrive - Vysok uen technick v Brn/kola/Druh ronk/2. semester/DE1/Digital-electronics-1/03-vivado/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_d_ff_rst_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
